Fix feature conflict in `num-traits` when building `emmylua_doc_cli`
Some cargo versions fail to resolve features for `num-traits`, resulting in no-std build and compilation error:

```
Compiling num-traits v0.2.19
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `std`
```

Explicitly adding `"std"` to `num-traits` features mitigates this problem.